# Generated by Django 4.0.6 on 2022-07-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Post', '0004_post_upload_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-upload_date']},
        ),
    ]
