# Generated by Django 4.0.6 on 2022-07-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0006_rename_profile_picture_userprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='new_user',
        ),
    ]
